---
- name: cloudblock - google cloud x86_64 variant
  hosts: localhost
  gather_facts: true
  become: true
  tasks:

    - name: required packages
      apt:
        pkg:
          - apache2
          - docker.io
          - libcap2-bin
          - python3-pip
          - ssl-cert
        state: latest
        update_cache: yes

    - name: docker python packages
      pip:
        name:
          - docker
        executable: /usr/bin/pip3
        state: latest

    - name: IP Forwarding enable/persist
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        state: present
        reload: yes
        sysctl_set: yes
        sysctl_file: /etc/sysctl.conf

    - name: docker service started/enabled
      systemd:
        name: docker
        state: started
        enabled: True

    - name: various container directories
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /opt/cloudflared
        - /opt/pihole
        - /opt/pihole/etc
        - /opt/pihole/dnsmasq.d

    - name: wireguard dir gets user ubuntu
      file:
        path: /opt/wireguard
        state: directory
        owner: ubuntu
        group: ubuntu

    - name: DoH Endpoints
      blockinfile:
        create: yes
        mode: '0644'
        path: /opt/cloudflared/endpoints
        block: |
          adguard https://dns.adguard.com/dns-query
          cloudflare https://cloudflare-dns.com/dns-query
          applied-privacy https://doh.applied-privacy.net/query
          google https://dns.google/dns-query
          hurricane-electric https://ordns.he.net/dns-query
          pi-dns https://doh.pi-dns.com/dns-query
          quad9-recommended https://dns.quad9.net/dns-query
          libre-dns https://doh.libredns.gr/dns-query
          opendns https://doh.opendns.com/dns-query

    - name: Set DoH URL from DoH provider var
      shell: |
        awk '/{{ doh_provider }}/ { print $2 }' /opt/cloudflared/endpoints
      register: doh_url

    - name: Retrieve GCS Token
      uri:
        url: http://metadata.google.internal/computeMetadata/v1/instance/service-accounts/default/token
        method: GET
        headers:
          Metadata-Flavor: Google
        return_content: yes
      register: gcs_token_resp

    - name: Get pihole secret from google secret manager
      uri:
        url: https://secretmanager.googleapis.com/v1/projects/{{ gcp_project_prefix }}-project-{{ gcp_project_suffix }}/secrets/pihole-web-password/versions/latest:access
        method: GET
        remote_src: yes
        return_content: yes
        headers:
          Authorization: Bearer {{ gcs_token_resp.json.access_token }}
          Content-Type: application/json
          x-goog-user-project: "{{ gcp_project_prefix }}-project-{{ gcp_project_suffix }}"
      register: ph_secret

    - name: Cloudflared Dockerfile
      blockinfile:
        create: yes
        mode: '0644'
        path: /opt/cloudflared/Dockerfile
        block: |
          FROM ubuntu:bionic
          EXPOSE 53/tcp
          EXPOSE 53/udp
          RUN apt-get update && \
              apt-get install -y wget && \
              wget https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 --directory-prefix=/usr/local/bin/ && \
              chmod 555 /usr/local/bin/cloudflared-linux-amd64
              ENTRYPOINT ["/usr/local/bin/cloudflared-linux-amd64", "proxy-dns","--address", "{{ docker_doh }}", "--port", "53", "--upstream", "{{ doh_url.stdout }}"]
      register: cloudflared_doh_dockerfile

    - name: Cloudflared image
      docker_image:
        name: cloudflared_doh
        build:
          path: /opt/cloudflared
        source: build
        force_source: yes
      when: cloudflared_doh_dockerfile.changed

# cloud + vpn = mtu restrictions that cause failures for sites like google.com or the play store
# a lower mtu fixes the problem
    - name: cloudflared pihole and wireguard network
      docker_network:
        name: piinthesky
        driver: bridge
        driver_options:
          com.docker.network.driver.mtu: 1380
        ipam_config:
          - subnet: "{{ docker_network }}/24"
            gateway: "{{ docker_gw }}"

    - name: cloudflared_doh container
      docker_container:
        name: cloudflared_doh
        image: cloudflared_doh
        networks:
          - name: piinthesky
            ipv4_address: "{{ docker_doh }}"
        purge_networks: yes
        restart_policy: "always"

    - name: pihole container - without DNS listen
      docker_container:
        name: pihole
        env:
          DNS1: 172.18.0.2
          DNS2: 172.18.0.2
          WEBPASSWORD: "{{ ph_secret.json.payload.data | b64decode }}"
        image: pihole/pihole:latest
        networks:
          - name: piinthesky
            ipv4_address: "{{ docker_pihole }}"
        ports:
          - "8001:80"
        volumes:
          - /opt/pihole/etc:/etc/pihole/:rw
          - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
        purge_networks: yes
        restart_policy: "always"
      when: dns_novpn == "0"
      no_log: True

    - name: pihole container - with DNS listen
      docker_container:
        name: pihole
        env:
          DNS1: 172.18.0.2
          DNS2: 172.18.0.2
          WEBPASSWORD: "{{ ph_secret.json.payload.data | b64decode }}"
        image: pihole/pihole:latest
        networks:
          - name: piinthesky
            ipv4_address: "{{ docker_pihole }}"
        ports:
          - "8001:80"
          - "53:53"
          - "53:53/udp"
        volumes:
          - /opt/pihole/etc:/etc/pihole/:rw
          - /opt/pihole/dnsmasq.d:/etc/dnsmasq.d:rw
        purge_networks: yes
        restart_policy: "always"
      when: dns_novpn == "1"
      no_log: True

    - name: wireguard container
      docker_container:
        name: wireguard
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Etc/UTC"
          SERVERURL: "auto"
          SERVERPORT: "51820"
          ALLOWEDIPS: "{{ docker_pihole }}"
          PEERS: "{{ wireguard_peers }}"
          PEERDNS: "{{ docker_pihole }}"
          INTERNAL_SUBNET: "{{ wireguard_network }}"
        image: linuxserver/wireguard:latest
        networks:
          - name: piinthesky
            ipv4_address: "{{ docker_wireguard }}"
        ports:
          - "51820:51820/udp"
        sysctls:
          net.ipv4.conf.all.src_valid_mark: 1
        volumes:
          - /opt/wireguard:/config:rw
        restart_policy: "always"
        purge_networks: yes

    - name: Enable Apache2 modules for proxy and ssl
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - headers
        - proxy
        - proxy_http
        - ssl
      register: apache_modules

    - name: Apache2 proxy configuration
      template:
        src: 8001-web-proxy.conf
        dest: /etc/apache2/sites-enabled/8001-web-proxy.conf
        owner: root
        group: root
        mode: 0444
      register: proxy_conf

    - name: Apache2 enabled / restarted
      systemd:
        name: apache2
        state: restarted
        enabled: yes
      when: apache_modules.changed or proxy_conf.changed

    - name: Set peer count list
      set_fact:
        peer_count: "{{range(1, wireguard_peers|int + 1) | list }}"

    - name: Wait for final peer conf (Wireguard)
      wait_for:
        path: "/opt/wireguard/peer{{ wireguard_peers }}/{{ item }}"
        state: present
        timeout: 600
        sleep: 1
      with_items:
        - "publickey-peer{{ wireguard_peers }}"
        - "privatekey-peer{{ wireguard_peers }}"
        - "peer{{ wireguard_peers }}.conf"
        - "peer{{ wireguard_peers }}.png"

    - name: Upload wireguard to google bucket - publickey
      uri:
        url: https://storage.googleapis.com/upload/storage/v1/b/{{ gcp_project_prefix }}-bucket-{{ gcp_project_suffix }}/o?uploadType=media&name=wireguard/peer{{ item }}/publickey-peer{{ item }}
        timeout: 720
        method: POST
        src: /opt/wireguard/peer{{ item }}/publickey-peer{{ item }}
        remote_src: yes
        return_content: yes
        headers:
          Authorization: Bearer {{ gcs_token_resp.json.access_token }}
          Content-Type: text/plain
      with_items:
        - "{{ peer_count }}"

    - name: Upload wireguard to google bucket - privatekey
      uri:
        url: https://storage.googleapis.com/upload/storage/v1/b/{{ gcp_project_prefix }}-bucket-{{ gcp_project_suffix }}/o?uploadType=media&name=wireguard/peer{{ item }}/privatekey-peer{{ item }}
        timeout: 720
        method: POST
        src: /opt/wireguard/peer{{ item }}/privatekey-peer{{ item }}
        remote_src: yes
        return_content: yes
        headers:
          Authorization: Bearer {{ gcs_token_resp.json.access_token }}
          Content-Type: text/plain
      with_items:
        - "{{ peer_count }}"

    - name: Upload wireguard to google bucket - conf
      uri:
        url: https://storage.googleapis.com/upload/storage/v1/b/{{ gcp_project_prefix }}-bucket-{{ gcp_project_suffix }}/o?uploadType=media&name=wireguard/peer{{ item }}/peer{{ item }}.conf
        timeout: 720
        method: POST
        src: /opt/wireguard/peer{{ item }}/peer{{ item }}.conf
        remote_src: yes
        return_content: yes
        headers:
          Authorization: Bearer {{ gcs_token_resp.json.access_token }}
          Content-Type: text/plain
      with_items:
        - "{{ peer_count }}"

    - name: Upload wireguard to google bucket - png
      uri:
        url: https://storage.googleapis.com/upload/storage/v1/b/{{ gcp_project_prefix }}-bucket-{{ gcp_project_suffix }}/o?uploadType=media&name=wireguard/peer{{ item }}/peer{{ item }}.png
        timeout: 720
        method: POST
        src: /opt/wireguard/peer{{ item }}/peer{{ item }}.png
        remote_src: yes
        return_content: yes
        headers:
          Authorization: Bearer {{ gcs_token_resp.json.access_token }}
          Content-Type: image/png
      with_items:
        - "{{ peer_count }}"
